# Generated by Django 5.2.5 on 2025-08-12 15:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("txid", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["wallet", "is_active"],
                        name="transaction_wallet__c5f48c_idx",
                    ),
                    models.Index(fields=["txid"], name="transaction_txid_482944_idx"),
                    models.Index(
                        fields=["created_at"], name="transaction_created_5c02ac_idx"
                    ),
                ],
            },
        ),
    ]
