# Generated by Django 5.2.5 on 2025-08-12 15:15

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="wallets_is_acti_3744ed_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="wallets_created_dceae9_idx"
                    ),
                ],
            },
        ),
    ]
